
@contentType = application/json
@url-encode=application/x-www-form-urlencoded
@apikey= ODZtfcy30GzyDrzIPQW8Pj5zGIG3i1AR
# UiiPmGYGhmu16N0fDmYWwN5co4bZVEpA # pavan	
# 22jTShR3IjnQOCCwSjnMcSwWQegvyz3M # kishore
# ODZtfcy30GzyDrzIPQW8Pj5zGIG3i1AR # seshu
# qANXbYNKbHCpeFRHAsVkU3gYhvEz6MIG # satyanadella
@greeter_url = http://192.168.1.142:5555
@KONG_BASE_URL = http://localhost:18000
@KONG_ADMIN_URL = http://192.168.1.142:18001

# @kong_greeter_url = {{KONG_BASE_URL}}/public
# @kong_greeter_url = {{KONG_BASE_URL}}/private/seshug
# @kong_greeter_url = {{KONG_BASE_URL}}/shared/ispace
@kong_greeter_url = {{KONG_BASE_URL}}/shared/comtech


#################### GET Echo ########################################  
# GET {{greeter_url}}/shared/comtech  HTTP/1.1
GET {{kong_greeter_url}}/?apikey={{apikey}}  HTTP/1.1
# GET http://localhost:5555/group  HTTP/1.1

Content-Type: {{contentType}}


#################### POST Echo ########################################  
# POST  {{greeter_url}}/echo  HTTP/1.1
POST {{kong_greeter_url}}/?apikey={{apikey}}  HTTP/1.1
Content-Type: {{contentType}}

{
    "message":"How are you doing ?"

}
#################### PUT Echo ########################################  
PUT {{greeter_url}}/public HTTP/1.1
# PUT {{kong_greeter_url}}/public HTTP/1.1
Content-Type: {{contentType}}

{
    "message":"How are you doing ?"

}

#################### PATCH Echo ########################################  
PATCH   {{greeter_url}}/public  HTTP/1.1
Content-Type: {{contentType}}

{
    "message":"How are you doing ?"

}
#################### DELETE Echo ########################################  
DELETE  {{greeter_url}}/public  HTTP/1.1
Content-Type: {{contentType}}

#########################################################################

#################### GET Home ########################################  
# GET {{greeter_url}}/private/user  HTTP/1.1
# GET {{greeter_url}}  HTTP/1.1
# GET {{KONG_BASE_URL}}/helloword  HTTP/1.1
GET {{KONG_BASE_URL}}/helloword?apikey=1iLXAex15SDLGY1DP9oBsZY4Xa1eN9VQ  HTTP/1.1
Content-Type: {{contentType}}

#########################################################################
######################### KONG ADMIN ####################################

######################### Create a Service ##################################################

# curl -X POST -H "Content-Type: application/json" \
#  -d '{ "name": "greeter","url": "http://127.0.0.1:5555/echo"}' \
#  http://192.168.1.149:18001/services/


POST {{KONG_ADMIN_URL}}/services HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "greeter",
    "url": "http://192.168.1.149:5555/echo"
}
######################### List all services  ##################################################
GET {{KONG_ADMIN_URL}}/services HTTP/1.1
# curl --location --request GET 'http://192.168.1.149:18001/services'

######################### Retrieve single service  ##################################################
GET {{KONG_ADMIN_URL}}/services/greeter HTTP/1.1

######################### Create a route ##################################################

curl --location --request POST 'http://192.168.1.142:18001/services/gatekeeper/routes' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'paths[]=/gatekeeper/v1' \
--data-urlencode 'strip_path=true' \
--data-urlencode 'name=gatekeeper'

################# List routes for a service #####################

GET {{KONG_ADMIN_URL}}/services/greeter/routes HTTP/1.1


# ###############################################

## Not Working!!!
# POST {{KONG_ADMIN_URL}}/services/greeter/routes HTTP/1.1
# Content-Type: {{url-encode}}

# { 
#     "name": "greeter-route",
#     "paths": ["/greeter/v1"],
#     "methods": ["GET"]

# }


################################################################################################
 curl --location --request DELETE 'http://192.168.1.149:18001/services/greeter'


################################################################################################

  Example Endpoint :  http://api.demo.location.studio/geo/maps/v2/mb/{resource-type}/{x-custom-id}/{filename}?api_key=<api_key>
  Example Header: X-Consumer-Id : <X-Consumer-Id>

1. Example Endpoint :  http://api.demo.location.studio/geo/maps/v2/mb/{resource-type}/{data_type}/{x-custom-id}/{filename}?api_key=<api_key>


1. Example Endpoint :  http://api.demo.location.studio/geo/maps/v2/mb/
                                    {resource-type}/{data_type}/{x-custom-id}/{filename}


1. Domain Name + RouteMatch (/geo/maps/v2/mb/) + RoutePath ==> Upstream (domain+path) + RoutePath


###############################################################

#version #2
{data_type}/{custom-id} 
              1. "shared/{group-name}" - variable (one for each company/group) | {x-custome-id} = group-name
              2. "private/username"  - constant string    | {x-custome-id} = consumer.name
              3. "public"   - constant string    | {x-custome-id} = consumer.name (plain key-auth plugin)

route_parameters
    - The name of route parameters must be made up of “word characters” ([A-Za-z0-9_]).
    - sending the consumer_name might not possible




# Tiles/sources/styles/sprites/fonts
Private: under <api-key> folder can be accessed by any user providing the same <api-key>.  
Public:  under "default" folder can be accessed by any user with any valid api-key.


# Deprecated
{data_type} - 1. {group-name} - variable (one for each company/group) | {x-custome-id} = group-name
              2. "private"  - constant string    | {x-custom-id} = consumer.name
              3. "public"   - constant string    | {x-custom-id} = consumer.name


