@contentType = application/json
# @token = "Bearer " + $token
@vermittler_base_url = http://localhost:4000

###### Status #######
GET {{vermittler_base_url}}/status HTTP/1.1

############# Song #####################
### Get song by slug
GET {{vermittler_base_url}}/songs/slug/song-1 HTTP/1.1

### Get all songs
GET {{vermittler_base_url}}/songs HTTP/1.1
### GET song by id
GET {{vermittler_base_url}}/songs/2 HTTP/1.1

### Create song
POST {{vermittler_base_url}}/songs HTTP/1.1
Content-Type: application/json

{
  "title": "song 3"
}

### Update song
PUT {{vermittler_base_url}}/songs/2 HTTP/1.1
Content-Type: application/json

{
  "title": "Devi Sri Prasad"
}

### Patch song
PATCH {{vermittler_base_url}}/songs/2 HTTP/1.1
Content-Type: application/json

{
  "title": "Devi Sri Prasad"
}

### DELETE song
DELETE {{vermittler_base_url}}/songs/35 HTTP/1.1
##########

